query {
  mySecretAnimal {
        id
        person {
            name
        }
        friend {
            person {
                name
            }
            animal {
                name
                description
            }
        }
    }
}